### ISSUE TITLE
ecore resource in readme not found

### ISSUE THREAD

**Issue by AnWeber** [maybeec/oomph-task-download#8]
Please update readme. Resource [https://raw.githubusercontent.com/maybeec/oomph-task-download/master/task-download-updatesite/model/Task-download-1.0.ecore](https://raw.githubusercontent.com/maybeec/oomph-task-download/master/task-download-updatesite/model/Task-download-1.0.ecore) does not exists.

Is there a working example setup for using this plugin?

**Comment by maybeec** [comment]
Hi, basically, this oomph download task has been deprecated (I should note it somewhere) as you can simply achieve that by already provided tasks of oomph. See an example here: https://github.com/devonfw/devon-ide/blob/master/docs/oomph/products/DevonIde.setup#L471

**Comment by AnWeber** [comment]
thanks for the information, but the link is also not working:-).

**Comment by maybeec** [comment]
ok sorry about that, I thought its an open repo. Take this: https://github.com/oasp/oasp4j-ide/blob/master/docs/oomph/products/OASP4J.setup#L168

**Comment by AnWeber** [comment]
Thanks for the great help. Exactly what I am searching for.

Malte Brunnlieb <notifications@github.com> schrieb am Di., 18. Sep. 2018,
16:11:
